### ISSUE TITLE
How to predict 3d box with PointPillars when point_cloud_range contains x<0

### ISSUE THREAD

**Issue by naah69** [isl-org/Open3D-ML#551]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D-ML/issues).
- [X] I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

when i modify `pointpillars_kitti.yml` to the below. the result is error.
```yaml
model:
  name: PointPillars
  ckpt_path: # path/to/your/checkpoint

  batcher: "ignore"

  point_cloud_range: [-69.12, -39.68, -3, 69.12, 39.68, 1]
...
  head:
    in_channels: 384
    feat_channels: 384
    nms_pre: 100
    score_thr: 0.1
    ranges: [
      [-70.4, -39.68, -0.6, 70.4, 39.68, -0.6],
      [-70.4, -39.68, -0.6, 70.4, 39.68, -0.6],
      [-70.4, -39.68, -1.78, 70.4, 39.68, -1.78]
    ]
...
  augment:
    PointShuffle: True
    ObjectRangeFilter:
      point_cloud_range: [-69.12, -39.68, -3, 69.12, 39.68, 1]
...
```

result like this:
<img width="1583" alt="image" src="https://user-images.githubusercontent.com/25682169/176589333-6be5a666-feb2-4913-9cbd-ee8f047ff0bb.png">
