### ISSUE TITLE
The performance of RandLA-Net trained on Semantic3D

### ISSUE THREAD

**Issue by srzxDragon** [isl-org/Open3D-ML#587]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D-ML/issues).
- [X] I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Thanks for your excellent work! I have a problem of reproducing the official results of  RandLA-Net trained on Semantic3D. I trained RandLA-Net on Semantic3d with official config file (ml3d/configs/randlanet_semantic3d.yml), but the result I got has a large gap below the official result. The following is the final training result and is this result reasonable for training? And which split is the official reported performance from, train, val or test? Looking forward for your reply.
![image](https://user-images.githubusercontent.com/87605861/220809027-869d280f-9aab-4163-a29f-09fa49073083.png)
```yml
dataset:
  name: Semantic3D
  dataset_path: # path/to/your/dataset
  cache_dir: ./logs/cache_small3d/
  class_weights: [5181602, 5012952, 6830086, 1311528, 10476365, 946982, 334860, 269353]
  ignored_label_inds: [0]
  num_points: 65536
  test_result_folder: ./test
  use_cache: true
  val_files:
  - bildstein_station1_xyz_intensity_rgb
  - domfountain_station1_xyz_intensity_rgb
  steps_per_epoch_train: 500
  steps_per_epoch_valid: 10
model:
  name: RandLANet
  batcher: DefaultBatcher
  ckpt_path: I set this as the weight file download from model_zoo.md
  num_neighbors: 16
  num_layers: 5
  num_points: 65536
  num_classes: 8
  ignored_label_inds: [0]
  sub_sampling_ratio: [4, 4, 4, 4, 2]
  in_channels: 6
  dim_features: 8
  dim_output: [16, 64, 128, 256, 512]
  grid_size: 0.06
  augment:
    recenter:
      dim: [0, 1]
    normalize:
      feat:
        method: linear
        bias: 0
        scale: 255
    rotate:
      method: vertical
    scale:
      min_s: 0.9
      max_s: 1.1
    noise:
      noise_std: 0.001
pipeline:
  name: SemanticSegmentation
  num_workers: 0
  pin_memory: False
  optimizer:
    lr: 0.001
  batch_size: 2
  main_log_dir: ./logs
  max_epoch: 100
  save_ckpt_freq: 5
  scheduler_gamma: 0.9886
  test_batch_size: 1
  train_sum_dir: train_log
  val_batch_size: 2
  summary:
    record_for: []
    max_pts:
    use_reference: false
    max_outputs: 1

```
